config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  scope "/admin" do
    resources :users
  end

  unauthenticated do
    get 'home/index'
  end

  authenticated do
  end

  get 'home/index'

  resources :near_places
  resources :place_facilities
  resources :place_costs
  resources :place_services
  resources :place_sports
  resources :places

  root to: 'home#index'
  

end

app/models/near_place.rb
class NearPlace < ActiveRecord::Base
  belongs_to :place

  rails_admin do
    configure :place do
      label 'Owner of this ball: '
    end
  end
end

app/controllers/near_places_controller.rb
class NearPlacesController < ApplicationController
  before_action :set_near_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /near_places
  # GET /near_places.json
  def index
    @near_places = NearPlace.all
  end

  # GET /near_places/1
  # GET /near_places/1.json
  def show
  end

  # GET /near_places/new
  def new
    @near_place = NearPlace.new
  end

  # GET /near_places/1/edit
  def edit
  end

  # POST /near_places
  # POST /near_places.json
  def create
    #@place = Place.find(@_params[:near_place][:place_id].to_i)
    #@near_place = @place.near_place.build(near_place_params)
    @near_place = NearPlace.new(near_place_params)

    respond_to do |format|
      if @near_place.save
        format.html { redirect_to @near_place, notice: 'Near place was successfully created.' }
        format.json { render :show, status: :created, location: @near_place }
      else
        format.html { render :new }
        format.json { render json: @near_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /near_places/1
  # PATCH/PUT /near_places/1.json
  def update
    respond_to do |format|
      if @near_place.update(near_place_params)
        format.html { redirect_to @near_place, notice: 'Near place was successfully updated.' }
        format.json { render :show, status: :ok, location: @near_place }
      else
        format.html { render :edit }
        format.json { render json: @near_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /near_places/1
  # DELETE /near_places/1.json
  def destroy
    @near_place.destroy
    respond_to do |format|
      format.html { redirect_to near_places_url, notice: 'Near place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_near_place
      @near_place = NearPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def near_place_params
      params.require(:near_place).permit(:kiosk, :disco, :beach, :national_park, :other, :place_id)
    end
end

app/helpers/near_places_helper.rb
module NearPlacesHelper
end

app/views/near_places/_form.html.erb
<%= form_for(@near_place) do |f| %>
  <% if @near_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@near_place.errors.count, "error") %> prohibited this near_place from being saved:</h2>

      <ul>
      <% @near_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kiosk %><br>
    <%= f.check_box :kiosk %>
  </div>
  <div class="field">
    <%= f.label :disco %><br>
    <%= f.check_box :disco %>
  </div>
  <div class="field">
    <%= f.label :beach %><br>
    <%= f.check_box :beach %>
  </div>
  <div class="field">
    <%= f.label :national_park %><br>
    <%= f.check_box :national_park %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.text_field :place_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/near_places/_near_places.html.erb
<p>
  <strong>Kiosk:</strong>
  <%= @place.near_place.kiosk %>
</p>

<p>
  <strong>Disco:</strong>
  <%= @place.near_place.disco %>
</p>

<p>
  <strong>Beach:</strong>
  <%= @place.near_place.beach %>
</p>

<p>
  <strong>National park:</strong>
  <%= @place.near_place.national_park %>
</p>

<p>
  <strong>Other:</strong>
  <%= @place.near_place.other %>
</p>

app/views/near_places/edit.html.erb
<h1>Editing Near Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @near_place %> |
<%= link_to 'Back', near_places_path %>

app/views/near_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Near Places</h1>

<table>
  <thead>
    <tr>
      <th>Kiosk</th>
      <th>Disco</th>
      <th>Beach</th>
      <th>National park</th>
      <th>Other</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @near_places.each do |near_place| %>
      <tr>
        <td><%= near_place.kiosk %></td>
        <td><%= near_place.disco %></td>
        <td><%= near_place.beach %></td>
        <td><%= near_place.national_park %></td>
        <td><%= near_place.other %></td>
        <td><%= near_place.place %></td>
        <td><%= link_to 'Show', near_place %></td>
        <td><%= link_to 'Edit', edit_near_place_path(near_place) %></td>
        <td><%= link_to 'Destroy', near_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Near place', new_near_place_path %>

app/views/near_places/new.html.erb
<h1>New Near Place</h1>

<%= render 'form' %>

<%= link_to 'Back', near_places_path %>

app/views/near_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kiosk:</strong>
  <%= @near_place.kiosk %>
</p>

<p>
  <strong>Disco:</strong>
  <%= @near_place.disco %>
</p>

<p>
  <strong>Beach:</strong>
  <%= @near_place.beach %>
</p>

<p>
  <strong>National park:</strong>
  <%= @near_place.national_park %>
</p>

<p>
  <strong>Other:</strong>
  <%= @near_place.other %>
</p>

<p>
  <strong>Place:</strong>
  <%= @near_place.place %>
</p>

<%= link_to 'Edit', edit_near_place_path(@near_place) %> |
<%= link_to 'Back', near_places_path %>