config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  scope "/admin" do
    resources :users
  end

  unauthenticated do
    get 'home/index'
  end

  authenticated do
  end

  get 'home/index'

  resources :near_places
  resources :place_facilities
  resources :place_costs
  resources :place_services
  resources :place_sports
  resources :places

  root to: 'home#index'
  

end

app/models/place_sport.rb
class PlaceSport < ActiveRecord::Base
  belongs_to :place
end

app/controllers/place_sports_controller.rb
class PlaceSportsController < ApplicationController
  before_action :set_place_sport, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /place_sports
  # GET /place_sports.json
  def index
    @place_sports = PlaceSport.all
  end

  # GET /place_sports/1
  # GET /place_sports/1.json
  def show
  end

  # GET /place_sports/new
  def new
    @place_sport = PlaceSport.new
  end

  # GET /place_sports/1/edit
  def edit
  end

  # POST /place_sports
  # POST /place_sports.json
  def create
    #@place = Place.find(@_params[:place_sport][:place_id].to_i)
    #@notification = @place.place_sport.build(place_sport_params)
    @place_sport = PlaceSport.new(place_sport_params)

    respond_to do |format|
      if @place_sport.save
        format.html { redirect_to @place_sport, notice: 'Place sport was successfully created.' }
        format.json { render :show, status: :created, location: @place_sport }
      else
        format.html { render :new }
        format.json { render json: @place_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_sports/1
  # PATCH/PUT /place_sports/1.json
  def update
    respond_to do |format|
      if @place_sport.update(place_sport_params)
        format.html { redirect_to @place_sport, notice: 'Place sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_sport }
      else
        format.html { render :edit }
        format.json { render json: @place_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_sports/1
  # DELETE /place_sports/1.json
  def destroy
    @place_sport.destroy
    respond_to do |format|
      format.html { redirect_to place_sports_url, notice: 'Place sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_sport
      @place_sport = PlaceSport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_sport_params
      params.require(:place_sport).permit(:ping_pong_table, :canoe, :soccer_field, :platform_tennis_court, :volleyball_court, :other, :place_id)
    end
end

app/helpers/place_sports_helper.rb
module PlaceSportsHelper
end

app/views/place_sports/_form.html.erb
<%= form_for(@place_sport) do |f| %>
  <% if @place_sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_sport.errors.count, "error") %> prohibited this place_sport from being saved:</h2>

      <ul>
      <% @place_sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ping_pong_table %><br>
    <%= f.check_box :ping_pong_table %>
  </div>
  <div class="field">
    <%= f.label :canoe %><br>
    <%= f.check_box :canoe %>
  </div>
  <div class="field">
    <%= f.label :soccer_field %><br>
    <%= f.check_box :soccer_field %>
  </div>
  <div class="field">
    <%= f.label :platform_tennis_court %><br>
    <%= f.check_box :platform_tennis_court %>
  </div>
  <div class="field">
    <%= f.label :volleyball_court %><br>
    <%= f.check_box :volleyball_court %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.text_field :place_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/place_sports/_place_sports.html.erb
<p>
  <strong>Ping pong table:</strong>
  <%= @place.place_sport.ping_pong_table %>
</p>

<p>
  <strong>Canoe:</strong>
  <%= @place.place_sport.canoe %>
</p>

<p>
  <strong>Soccer field:</strong>
  <%= @place.place_sport.soccer_field %>
</p>

<p>
  <strong>Platform tennis court:</strong>
  <%= @place.place_sport.platform_tennis_court %>
</p>

<p>
  <strong>Volleyball court:</strong>
  <%= @place.place_sport.volleyball_court %>
</p>

<p>
  <strong>Other:</strong>
  <%= @place.place_sport.other %>
</p>

app/views/place_sports/edit.html.erb
<h1>Editing Place Sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @place_sport %> |
<%= link_to 'Back', place_sports_path %>

app/views/place_sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Place Sports</h1>

<table>
  <thead>
    <tr>
      <th>Ping pong table</th>
      <th>Canoe</th>
      <th>Soccer field</th>
      <th>Platform tennis court</th>
      <th>Volleyball court</th>
      <th>Other</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_sports.each do |place_sport| %>
      <tr>
        <td><%= place_sport.ping_pong_table %></td>
        <td><%= place_sport.canoe %></td>
        <td><%= place_sport.soccer_field %></td>
        <td><%= place_sport.platform_tennis_court %></td>
        <td><%= place_sport.volleyball_court %></td>
        <td><%= place_sport.other %></td>
        <td><%= place_sport.place %></td>
        <td><%= link_to 'Show', place_sport %></td>
        <td><%= link_to 'Edit', edit_place_sport_path(place_sport) %></td>
        <td><%= link_to 'Destroy', place_sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place sport', new_place_sport_path %>

app/views/place_sports/new.html.erb
<h1>New Place Sport</h1>

<%= render 'form' %>

<%= link_to 'Back', place_sports_path %>

app/views/place_sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ping pong table:</strong>
  <%= @place_sport.ping_pong_table %>
</p>

<p>
  <strong>Canoe:</strong>
  <%= @place_sport.canoe %>
</p>

<p>
  <strong>Soccer field:</strong>
  <%= @place_sport.soccer_field %>
</p>

<p>
  <strong>Platform tennis court:</strong>
  <%= @place_sport.platform_tennis_court %>
</p>

<p>
  <strong>Volleyball court:</strong>
  <%= @place_sport.volleyball_court %>
</p>

<p>
  <strong>Other:</strong>
  <%= @place_sport.other %>
</p>

<p>
  <strong>Place:</strong>
  <%= @place_sport.place %>
</p>

<%= link_to 'Edit', edit_place_sport_path(@place_sport) %> |
<%= link_to 'Back', place_sports_path %>