config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  scope "/admin" do
    resources :users
  end

  unauthenticated do
    get 'home/index'
  end

  authenticated do
  end

  get 'home/index'

  resources :near_places
  resources :place_facilities
  resources :place_costs
  resources :place_services
  resources :place_sports
  resources :places

  root to: 'home#index'
  

end

app/models/place_service.rb
class PlaceService < ActiveRecord::Base
  belongs_to :place
end

app/controllers/place_services_controller.rb
class PlaceServicesController < ApplicationController
  before_action :set_place_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /place_services
  # GET /place_services.json
  def index
    @place_services = PlaceService.all
  end

  # GET /place_services/1
  # GET /place_services/1.json
  def show
  end

  # GET /place_services/new
  def new
    @place_service = PlaceService.new
  end

  # GET /place_services/1/edit
  def edit
  end

  # POST /place_services
  # POST /place_services.json
  def create
    @place_service = PlaceService.new(place_service_params)

    respond_to do |format|
      if @place_service.save
        format.html { redirect_to @place_service, notice: 'Place service was successfully created.' }
        format.json { render :show, status: :created, location: @place_service }
      else
        format.html { render :new }
        format.json { render json: @place_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_services/1
  # PATCH/PUT /place_services/1.json
  def update
    respond_to do |format|
      if @place_service.update(place_service_params)
        format.html { redirect_to @place_service, notice: 'Place service was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_service }
      else
        format.html { render :edit }
        format.json { render json: @place_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_services/1
  # DELETE /place_services/1.json
  def destroy
    @place_service.destroy
    respond_to do |format|
      format.html { redirect_to place_services_url, notice: 'Place service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_service
      @place_service = PlaceService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_service_params
      params.require(:place_service).permit(:dry_cleaning, :public_transport, :other, :place_id)
    end
end

app/helpers/place_services_helper.rb
module PlaceServicesHelper
end

app/views/place_services/_form.html.erb
<%= form_for(@place_service) do |f| %>
  <% if @place_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_service.errors.count, "error") %> prohibited this place_service from being saved:</h2>

      <ul>
      <% @place_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dry_cleaning %><br>
    <%= f.check_box :dry_cleaning %>
  </div>
  <div class="field">
    <%= f.label :public_transport %><br>
    <%= f.text_field :public_transport %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.text_field :place_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/place_services/_place_services.html.erb
<p>
  <strong>Dry cleaning:</strong>
  <%= @place.place_service.dry_cleaning %>
</p>

<p>
  <strong>Public transport:</strong>
  <%= @place.place_service.public_transport %>
</p>

<p>
  <strong>Other:</strong>
  <%= @place.place_service.other %>
</p>

app/views/place_services/edit.html.erb
<h1>Editing Place Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @place_service %> |
<%= link_to 'Back', place_services_path %>

app/views/place_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Place Services</h1>

<table>
  <thead>
    <tr>
      <th>Dry cleaning</th>
      <th>Public transport</th>
      <th>Other</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_services.each do |place_service| %>
      <tr>
        <td><%= place_service.dry_cleaning %></td>
        <td><%= place_service.public_transport %></td>
        <td><%= place_service.other %></td>
        <td><%= place_service.place %></td>
        <td><%= link_to 'Show', place_service %></td>
        <td><%= link_to 'Edit', edit_place_service_path(place_service) %></td>
        <td><%= link_to 'Destroy', place_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place service', new_place_service_path %>

app/views/place_services/new.html.erb
<h1>New Place Service</h1>

<%= render 'form' %>

<%= link_to 'Back', place_services_path %>

app/views/place_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dry cleaning:</strong>
  <%= @place_service.dry_cleaning %>
</p>

<p>
  <strong>Public transport:</strong>
  <%= @place_service.public_transport %>
</p>

<p>
  <strong>Other:</strong>
  <%= @place_service.other %>
</p>

<p>
  <strong>Place:</strong>
  <%= @place_service.place %>
</p>

<%= link_to 'Edit', edit_place_service_path(@place_service) %> |
<%= link_to 'Back', place_services_path %>