config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  scope "/admin" do
    resources :users
  end

  unauthenticated do
    get 'home/index'
  end

  authenticated do
  end

  get 'home/index'

  resources :near_places
  resources :place_facilities
  resources :place_costs
  resources :place_services
  resources :place_sports
  resources :places

  root to: 'home#index'
  

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_one :place_facility
	has_one :place_sport
	has_one :near_place
	has_one :place_cost
	has_one :place_service

	validates :name, :description, :country, :state, :vacancy, presence: true
	reverse_geocoded_by :latitude, :longitude

	DISQUS_SHORTNAME = Rails.env == "development" ? "gocampingapp".freeze : "gocampingapp".freeze
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    filter_by_country if params[:search]
    @places = Place.all unless params[:search]
  end

  def filter_by_country
    pais = params[:search]
    @places = Place.where(country: pais)
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
			marker.lat place.latitude
			marker.lng place.longitude
			marker.infowindow "<a href='/places/"+"#{place.id}"+"'>#{place.name}, #{place.state}</a>"
			marker.json({ title: place.name, id: place.id })
		end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @hash = Gmaps4rails.build_markers(@place) do |place, marker|
		  marker.lat place.latitude
		  marker.lng place.longitude
		  marker.infowindow "<a target='blank' href='https://www.google.com/maps/place/"+"#{place.state}"+"'>Get Directions With Google Maps</a>"
		  marker.json({ title: place.name })
		end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :latitude, :longitude, :country, :state)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label' %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :latitude , class: 'control-label'%><br>
    <%= f.text_field :latitude, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: 'control-label' %><br>
    <%= f.text_field :longitude, class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="actions">
      <%= f.submit ' Public place', class: 'btn btn-primary glyphicon glyphicon-plus' %>
  </div>
<% end %>

app/views/places/_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
	provider: { mapTypeId: google.maps.MapTypeId.HYBRID, maxZoom: 16 },
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/places/_place_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
	provider: { mapTypeId: google.maps.MapTypeId.HYBRID },
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(16);
});
</script>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<!-- Page Content -->
<div class="container">
  <!-- Page Header -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Places for camp
              <small>-Mom: WTF! backpackers camping in our backyard</small>
          </h1>
          <% if @hash %>
            <div style='width: 800px;'>
              <div id="map" style='width: 800px; height: 400px;'>
                <%= render 'map' %>
              </div>
            </div>
          <% end %>
      </div>
  </div>
  <!-- /.row -->

  <div class="row">

  <% @places.each do |place| %>
  <!-- Projects Row -->
        <div class="col-md-6 portfolio-item">
          <a href="<%= place_path(place) %>">
              <img class="img-responsive" src="<%= place.feature_image %>" alt="">
          </a>
          <h3>
              <a href="<%= place_path(place) %>"><%= place.name %></a>
               <small><%= place.state.capitalize %> (<%= place.country.capitalize %>)<%= " - $ " + place.place_cost.price.to_s if place.place_cost  %></small>
          </h3>
          <p><%= place.description %></p>
          <p><a href="<%= place_path(place) %>">Read more</a></p>
      </div>
      <% end %>
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/places/new.html.erb
<h1 class="glyphicon glyphicon-tent"> New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', :back, class: "btn btn-default"  %>

app/views/places/show.html.erb
 <!-- Page Content -->
<div class="container">

  <div class="row">
    <div class="col-md-3">
      <p class="lead">GoCamp Backpackers</p>
      <div class="list-group">
        <a href="<%= places_path %>" class="list-group-item active">Camps</a>
      </div>
    </div>

    <div class="col-md-9">
      <div class="thumbnail">
        <img class="img-responsive" src="<%= @place.feature_image %>" alt="">
        <div class="caption-full">
          <h4 class="pull-right"><%= "$ #{@place.place_cost.price}" if @place.place_cost %></h4>
          <h4><a href="#"><%= @place.name %></a>
          </h4>
          <p><%= @place.description %></p>
          <p class="glyphicon glyphicon-flag"> Country: <%= @place.country %>
          - <span class="glyphicon glyphicon-map-marker" > State:</span> <strong><%= @place.state %></strong></p>
          <p><span class="glyphicon glyphicon-globe" > Latitude </span><%= @place.latitude %>
           - <span class="glyphicon glyphicon-globe" > Longitude </span><%= @place.longitude %></p>
          <p><span class="glyphicon glyphicon-eye-open"> VACANCY: </span> <strong><%= @place.vacancy %></strong></p>

          <div style='width: 100%;'>
            <div id="map" style='width: 100%; height: 300px;'>
              <%= render 'place_map' %>
            </div>
          </div>
          <hr>
          <!-- ACA los otros modelos -->
          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <!-- //panel -->
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Facilities
                  </a>
                </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                  <%= render partial: "place_facilities/facilities", object: @place if @place.place_facility %>
                </div>
              </div>
            </div>
            <!-- //panel -->
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">
                  <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Sport / Enterteiment
                  </a>
                </h4>
              </div>
              <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                  <%= render partial: "place_sports/place_sports", object: @place if @place.place_sport %>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingThree">
                <h4 class="panel-title">
                  <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Near Places / Bussines
                  </a>
                </h4>
              </div>
              <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body">
                  <ul>
                  <% @place.nearbys(10).each do |place| %>
                    <li><%= link_to place.name, place %> (<%= place.distance.round(2) %>) miles</li>
                  <% end %>
                  </ul>
                  <%= render partial: "near_places/near_places", object: @place if @place.near_place %>
                </div>
              </div>
            </div>
            <!-- //panel -->
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingFour">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="true" aria-controls="collapseOne">
                    Services
                  </a>
                </h4>
              </div>
              <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                <div class="panel-body">
                  <%= render partial: "place_services/place_services", object: @place if @place.place_service %>
                </div>
              </div>
            </div>
            <!-- //panel -->
                        <!-- //panel -->
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingFive">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="true" aria-controls="collapseOne">
                    Costs
                  </a>
                </h4>
              </div>
              <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                <div class="panel-body">
                  <%= render partial: "place_costs/place_costs", object: @place if @place.place_cost %>
                </div>
              </div>
            </div>
            <!-- //panel -->
          </div>
<!-- // fin otros modelos -->

        </div>
        <div class="ratings">
          <a href="#" class="btn btn-success">Reserve this place</a>
          <p class="pull-right"><a href='<%= url_for(action: 'show', controller: 'places', only_path: false, protocol: 'http') %>#disqus_thread'></a></p>
          <p>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            4.0 stars
          </p>
        </div>
      </div>

        <div class="well">
            <div class="text-right">
                <p>Leave a Review</p>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                 <%= render partial: "disqus/thread", object: @place %>
                </div>
            </div>
        </div>

    </div>

  </div>

</div>
<!-- /.container -->

<div class="container">

    <hr>




<%= link_to ' Edit', edit_place_path(@place), class: 'btn btn-primary glyphicon glyphicon-pencil' %> |
<%= link_to ' Back', :back, class: 'btn btn-default' %>